### ISSUE TITLE
Set username, password and clientid in the configuration

### ISSUE THREAD

**Issue by GerManMcBrain** [bofeizhu/swift-nio-mqtt#56]
In the configuration I can set only the host, port and qos. I need to set the clientid, username and password also. 
It's possible to add this parameters to the init function of the configuration?

---
MQTTCodec.ConnectPacket.Payload(clientId: "HealthTap", willMessage: nil, username: nil, password: nil)))

**Comment by bofeizhu** [comment]
@GerManMcBrain Yes, of course! This project is still a WIP. I'm planning to do the first beta release by the end of this month, which will definitely address this issue. You are also welcome to submit PRs.

**Comment by GerManMcBrain** [comment]
@bofeizhu Can you give me access to create a branch for a PR. Or create a branch for me.
i did my changes and want to commit.

**Comment by bofeizhu** [comment]
@GerManMcBrain You can submit your PR to this repo from your fork.

**Comment by bofeizhu** [comment]
@GerManMcBrain I updated the Configuration struct with the new fields.

**Comment by GerManMcBrain** [comment]
@bofeizhu I approved your changes with my watchOS (6.1) project. its working very well. thx. 

I tried different swift packages (CocoaMQTT, MQTTKit, Mqtt, LightMQTT, NextMQTT) on gitHub. Your package is the first one which is working like I expected for watchOS. 

You can add in the readme that the NIOMQTT-Package is working with watchOS.
